imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: '@GDSiteBundle/Resources/config/services.yml' }
    - { resource: '@GDAdminBundle/Resources/config/services.yml' }

framework:
    #esi: ~
    translator: { fallback: %locale% }
    secret: %secret%
    charset: UTF-8
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    form: true
    csrf_protection: true
    validation: { enable_annotations: true }
    templating: { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start: true

# Twig Configuration
twig:
    debug: %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        MINIMUM_WITHDRAWAL_AMOUNT: 20
        CURRENCY: €
        facebook_link: http://www.facebook.com/pages/Conso-Acteur/227162690738898
        twitter_link: https://twitter.com/Conso_Acteur
        enabled : true
        default_locale : %locale%

# Assetic Configuration
assetic:
    debug: %kernel.debug%
    use_controller: false
    bundles: [ ]
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        # jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        # jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            default:
                driver: %database_driver%
                host: %database_host%
                port: %database_port%
                dbname: %database_name%
                user: %database_user%
                password: %database_password%
                charset: UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host: %mailer_host%
    username: %mailer_user%
    password: %mailer_password%

jms_security_extra:
    secure_all_services: false
    expressions: true

stof_doctrine_extensions:
    default_locale: en_US
    translation_fallback: true
    orm:
        default:
            timestampable: true
            sluggable: true
            translatable: true
            loggable: true

# Imagine Bundle configuration
liip_imagine:
    driver:               gd
    web_root:             %kernel.root_dir%/../web
    data_root:            %kernel.root_dir%/../web/uploads/merchants/images
    filter_sets:
        sidebarthumb:
            quality: 100
            path: sidebar 
            filters:
                thumbnail: { size: [72,40], mode: inset }                
        descriptionthumb:
            quality: 100
            path: main
            filters:
                thumbnail: { size: [90,50], mode: inset }
        flagthumb:
            quality: 100
            path: flag
            filters:
                thumbnail: { size: [16,16], mode: inset }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main    
    user_class:     GD\AdminBundle\Entity\User

    group:
        group_class: GD\AdminBundle\Entity\Group
    
    registration:
        form:
            type: site_user_registration
            #handler: site_user.form.handler.registration
        confirmation:
            enabled:    true
            from_email: { address : noreply@conso-acteur.com, sender_name : 'Conso-Acteur'}
             
    resetting:
       #in seconds
       token_ttl: 3600

sonata_user:
    security_acl: false
    class:
        user:         GD\AdminBundle\Entity\User
        group:        GD\AdminBundle\Entity\Group

sonata_admin:
    security:
        handler: sonata.admin.security.handler.role
        # role security information
        information:
            EDIT: EDIT
            LIST: LIST
            CREATE: CREATE
            VIEW: VIEW
            DELETE: DELETE
            OPERATOR: OPERATOR
            MASTER: MASTER
            ARCHIVE: ARCHIVE
            BLACKLIST: BLACKLIST
            APPROVE: APPROVE
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }

        groups:
            pages:
                label: Pages
                items: [gd_admin.page]
            categories:
                label: Categories/Tags
                items: [gd_admin.category, gd_admin.tag]
            merchants:
                label: Merchants
                items: [gd_admin.merchant, gd_admin.merchant_list, gd_admin.carousel_list, gd_admin.feedback, gd_admin.merchant_archived]
            offers:
                label: Offers
                items: [gd_admin.offer_cashback, gd_admin.offer_reimbursement, gd_admin.offer_codepromo, gd_admin.offer_subscription, gd_admin.offer_archived]
            customers:
                label: Customers
                items: [gd_admin.customer_details, gd_admin.customers_blacklisted, gd_admin.customers_archived, gd_admin.request]
            users:
                label: Users
                items: [sonata.user.admin.user, sonata.user.admin.group]
            withdrawals:
                label: Withdrawals
                items: [gd_admin.withdrawal_pending, gd_admin.withdrawal_approved, gd_admin.withdrawal_paid, gd_admin.withdrawal_on_hold ]
            transactions:
                label: Transactions
                items: [gd_admin.transaction]
            modules:
                label: Menu
                items: [gd_admin.module]
            others:
                label: Other
                items: [gd_admin.newsletter]

    title:      GreatDeals
    title_logo: /bundles/sonataadmin/logo_title.png
    templates:
        # default global templates
        layout:  GDAdminBundle::layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default actions templates, should extend a global templates
        list:    GDAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    GDAdminBundle:CRUD:edit.html.twig

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

fos_js_routing:
    routes_to_expose: [ gd_merchant_list, gd_merchant_show, gd_admin_get_categories_from_tag_json, gd_site_user_registration_confirmed, gd_offers_usage ]

white_october_breadcrumbs: ~
     
parameters:
    withdrawal_bank_type: 1
    withdrawal_cheque_type: 3
    withdrawal_paypal_type: 4
    bank_withdrawal_limit: 20
    cheque_withdrawal_limit: 40
    paypal_withdrawal_limit: 20
    flag_url: bundles/gdsite/images/lang/france.png
    country_code: { full_name: France, locale_name: Fr }
    languages:
        Fr: { full_name: French, locale_name: fr}
    fallback_language: fr 
    currency: €
    joining_bonus: 5
    referral_bonus: 5
    default_user : greatdeals
    support_email: adherent@conso-acteur.com