<?php

namespace GD\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackRepository extends EntityRepository
{

  /**
   * This function returns the approved feedbacks of the merchant to be displayed in the frontend.
   * 
   * @param Merchant $merchant
   * @return array 
   */
  public function getMerchantFeedbacks($merchant)
  {
       $query = $this->getEntityManager()
            ->createQuery('SELECT f FROM GD\AdminBundle\Entity\Feedback f WHERE f.merchant = :merchant AND f.isApproved = true AND f.isRejected = false ORDER BY f.createdAt DESC')
            ->setParameter('merchant', $merchant->getId());

        return $query->getResult();
  }
}