<?php

namespace GD\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MerchantTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MerchantTranslationRepository extends EntityRepository
{
}
