<?php

namespace GD\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsLetterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterRepository extends EntityRepository
{
  
    public function getSubscribedNewsletterUsers($email)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT n FROM GDAdminBundle:Newsletter n WHERE n.email = :email AND n.isSubscribed = 1')
            ->setParameter('email', $email);

        return $query->getResult();
    }
}
