<?php

namespace GD\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageTranslationRepository extends EntityRepository
{
    public function getTranslatedContent($slug, $locale)
    {
        $query = $this->createQueryBuilder('t')
            ->select()
            ->leftJoin('t.page', 'p')
            ->leftJoin('t.language', 'l')
            ->where('p.slug = :slug')
            ->andWhere('l.code = :locale')
            ->setParameter('slug', $slug)
            ->setParameter('locale', $locale)
            ->groupBy('t.page')
            ->getQuery();

        return $query->getSingleResult();
    }
}
