<?php

namespace GD\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReferralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferralRepository extends EntityRepository
{
  
    public function getSubscribedReferralUsers($user)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT u FROM GD\AdminBundle\Entity\User u WHERE u.email IN 
                            (SELECT r.referralEmail FROM GD\AdminBundle\Entity\Referral r WHERE r.user = :user)')
            ->setParameter('user', $user);

        return $query->getResult();
    }
    
    public function updateReferralDate($referralEmail)
    {
        $query = $this->getEntityManager()
            ->createQuery('UPDATE GD\AdminBundle\Entity\Referral r SET r.createdAt = CURRENT_TIMESTAMP() WHERE r.referralEmail = :referralEmail')
            ->setParameter('referralEmail', $referralEmail);

        return $query->getResult();
    }
}
