imports:
    - { resource: "../config.yml" }
    - { resource: parameters.ini }

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            default:
                driver: %database_driver%
                host: %database_host%
                port: %database_port%
                dbname: %database_name%
                user: %database_user%
                password: %database_password%
                charset: UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: true
            
# Twig Configuration
twig:
    globals:
        facebook_link: http://facebook.com
        twitter_link: http://twitter.com
        CURRENCY: $

parameters:
    flag_url: bundles/gdsite/images/lang/france.png
    country_code: { full_name: France, locale_name: Fr }
    languages: 
        En: { full_name: English, locale_name: en}
        Fr: { full_name: French, locale_name: fr}
