<?php

namespace GD\AdminBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use GD\AdminBundle\Entity\Offer;
use Doctrine\Common\Persistence\ObjectManager;

class LoadOfferData extends AbstractFixture implements OrderedFixtureInterface
{
    public function load(ObjectManager $manager)
    {
//        $cbOffer01 = new Offer();
//        $cbOffer01->setName("Cashback Offer");
//        $cbOffer01->setMerchant($this->getReference('merc-01'));
//        $cbOffer01->setType(Offer::OFFER_TYPE_CASHBACK);
//        $cbOffer01->setTranslatableLocale("en");
//        $cbOffer01->setDescription("This is Merchant 01's Cashback Offer number 01");
//        $cbOffer01->setProgramId("01");
//        $cbOffer01->setRedirectionUri("http://someRedirectionURL.com/01");
//        $cbOffer01->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//        $cbOffer01->setStartDate(new \DateTime('now'));
//        $cbOffer01->setEndDate(new \DateTime('tomorrow'));
//        $cbOffer01->setUserGainValue("Upto 7%");
//        $cbOffer01->setUserGainPercentage(50);
//        $cbOffer01->setIsCurrent(true);
//        $cbOffer01->setIsArchived(false);
//        $cbOffer01->setCreatedAt(new \DateTime());
//        $cbOffer01->setUpdatedAt(new \DateTime());
//        $cbOffer01->setArchivedAt(new \DateTime());
//        $cbOffer01->setCashbackValuePercentage(7);
//        $cbOffer01->setCashbackValueAmount(11);
//        $manager->persist($cbOffer01);
//
//        $cbOffer02 = new Offer();
//        $cbOffer02->setName("Cashback Offer 02");
//        $cbOffer02->setMerchant($this->getReference('merc-04'));
//        $cbOffer02->setType(Offer::OFFER_TYPE_CASHBACK);
//        $cbOffer02->setTranslatableLocale("en");
//        $cbOffer02->setDescription("This is Merchant 04's Cashback Offer number 02");
//        $cbOffer02->setProgramId("02");
//        $cbOffer02->setRedirectionUri("http://someRedirectionURL.com/02");
//        $cbOffer02->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//        $cbOffer02->setStartDate(new \DateTime('now'));
//        $cbOffer02->setEndDate(new \DateTime('tomorrow'));
//        $cbOffer02->setUserGainValue("Upto 11€");
//        $cbOffer02->setUserGainPercentage(50);
//        $cbOffer02->setIsCurrent(true);
//        $cbOffer02->setIsArchived(false);
//        $cbOffer02->setCreatedAt(new \DateTime());
//        $cbOffer02->setUpdatedAt(new \DateTime());
//        $cbOffer02->setArchivedAt(new \DateTime());
//        $cbOffer02->setCashbackValueAmount(12);
//        $manager->persist($cbOffer02);
//
//
//        $cbOffer03 = new Offer();
//        $cbOffer03->setName("Cashback Offer 03");
//        $cbOffer03->setMerchant($this->getReference('merc-03'));
//        $cbOffer03->setType(Offer::OFFER_TYPE_CASHBACK);
//        $cbOffer03->setTranslatableLocale("en");
//        $cbOffer03->setDescription("This is Merchant 03's Cashback Offer number 03");
//        $cbOffer03->setProgramId("03");
//        $cbOffer03->setRedirectionUri("http://someRedirectionURL.com/03");
//        $cbOffer03->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//        $cbOffer03->setStartDate(new \DateTime('now'));
//        $cbOffer03->setEndDate(new \DateTime('tomorrow'));
//        $cbOffer03->setUserGainValue("Upto 13€");
//        $cbOffer03->setUserGainPercentage(50);
//        $cbOffer03->setIsCurrent(true);
//        $cbOffer03->setIsArchived(false);
//        $cbOffer03->setCreatedAt(new \DateTime());
//        $cbOffer03->setUpdatedAt(new \DateTime());
//        $cbOffer03->setArchivedAt(new \DateTime());
//        $cbOffer03->setCashbackValueAmount(13);
//        $manager->persist($cbOffer03);
//
//        $cpOffer04 = new Offer();
//        $cpOffer04->setName("Code Promo Offer 04");
//        $cpOffer04->setMerchant($this->getReference('merc-02'));
//        $cpOffer04->setType(Offer::OFFER_TYPE_CODE_PROMO);
//        $cpOffer04->setTranslatableLocale("en");
//        $cpOffer04->setDescription("This is Merchant 02's Code Promo Offer number 04");
//        $cpOffer04->setProgramId("04");
//        $cpOffer04->setRedirectionUri("http://someRedirectionURL.com/04");
//        $cpOffer04->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//        $cpOffer04->setStartDate(new \DateTime('now'));
//        $cpOffer04->setEndDate(new \DateTime('tomorrow'));
//        $cpOffer04->setUserGainValue("CODE2233");
//        $cpOffer04->setIsCurrent(true);
//        $cpOffer04->setIsArchived(false);
//        $cpOffer04->setCreatedAt(new \DateTime());
//        $cpOffer04->setUpdatedAt(new \DateTime());
//        $cpOffer04->setArchivedAt(new \DateTime());
//        $manager->persist($cpOffer04);
//
//        $cpOffer05 = new Offer();
//        $cpOffer05->setName("Code Promo Offer 05");
//        $cpOffer05->setMerchant($this->getReference('merc-02'));
//        $cpOffer05->setType(Offer::OFFER_TYPE_CODE_PROMO);
//        $cpOffer05->setTranslatableLocale("en");
//        $cpOffer05->setDescription("This is Merchant 02's Code Promo Offer number 05");
//        $cpOffer05->setProgramId("05");
//        $cpOffer05->setRedirectionUri("http://someRedirectionURL.com/05");
//        $cpOffer05->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//        $cpOffer05->setStartDate(new \DateTime('now'));
//        $cpOffer05->setEndDate(new \DateTime('tomorrow'));
//        $cpOffer05->setUserGainValue("CODE2233");
//        $cpOffer05->setIsCurrent(true);
//        $cpOffer05->setIsArchived(false);
//        $cpOffer05->setCreatedAt(new \DateTime());
//        $cpOffer05->setUpdatedAt(new \DateTime());
//        $cpOffer05->setArchivedAt(new \DateTime());
//        $manager->persist($cpOffer05);
//
//        $cpOffer06 = new Offer();
//        $cpOffer06->setName("Code Promo Offer 06");
//        $cpOffer06->setMerchant($this->getReference('merc-02'));
//        $cpOffer06->setType(Offer::OFFER_TYPE_CODE_PROMO);
//        $cpOffer06->setTranslatableLocale("en");
//        $cpOffer06->setDescription("This is Merchant 02's Code Promo Offer number 06");
//        $cpOffer06->setProgramId("06");
//        $cpOffer06->setRedirectionUri("http://someRedirectionURL.com/06");
//        $cpOffer06->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//        $cpOffer06->setStartDate(new \DateTime('now'));
//        $cpOffer06->setEndDate(new \DateTime('tomorrow'));
//        $cpOffer06->setUserGainValue("CODE2233");
//        $cpOffer06->setIsCurrent(true);
//        $cpOffer06->setIsArchived(false);
//        $cpOffer06->setCreatedAt(new \DateTime());
//        $cpOffer06->setUpdatedAt(new \DateTime());
//        $cpOffer06->setArchivedAt(new \DateTime());
//        $manager->persist($cpOffer06);
//
//        $cpOffer07 = new Offer();
//        $cpOffer07->setName("Code Promo Offer 07");
//        $cpOffer07->setMerchant($this->getReference('merc-02'));
//        $cpOffer07->setType(Offer::OFFER_TYPE_CODE_PROMO);
//        $cpOffer07->setTranslatableLocale("en");
//        $cpOffer07->setDescription("This is Merchant 02's Code Promo Offer number 07");
//        $cpOffer07->setProgramId("07");
//        $cpOffer07->setRedirectionUri("http://someRedirectionURL.com/07");
//        $cpOffer07->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//        $cpOffer07->setStartDate(new \DateTime('now'));
//        $cpOffer07->setEndDate(new \DateTime('tomorrow'));
//        $cpOffer07->setUserGainValue("CODE2233");
//        $cpOffer07->setIsCurrent(true);
//        $cpOffer07->setIsArchived(false);
//        $cpOffer07->setCreatedAt(new \DateTime());
//        $cpOffer07->setUpdatedAt(new \DateTime());
//        $cpOffer07->setArchivedAt(new \DateTime());
//        $manager->persist($cpOffer07);
//        /*
//                $frOffer08 = new Offer();
//                $frOffer08->setName("Full Reimbursement Offer 08");
//                $frOffer08->setMerchant($this->getReference('merc-03'));
//                $frOffer08->setType(Offer::OFFER_TYPE_FULL_REIMBURSEMENT);
//                $frOffer08->setTranslatableLocale("en");
//                $frOffer08->setDescription("This is Merchant 03's Full Reimbursement Offer number 08");
//                $frOffer08->setProgramId("08");
//                $frOffer08->setRedirectionUri("http://someRedirectionURL.com/08");
//                $frOffer08->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//                $frOffer08->setStartDate(new \DateTime('now'));
//                $frOffer08->setEndDate(new \DateTime('tomorrow'));
//                $frOffer08->setUserGainValue("Upto 100€");
//                $frOffer08->setIsCurrent(true);
//                $frOffer08->setIsArchived(false);
//                $frOffer08->setCreatedAt(new \DateTime());
//                $frOffer08->setUpdatedAt(new \DateTime());
//                $frOffer08->setArchivedAt(new \DateTime());
//                $frOffer08->setCashbackValuePercentage(7);
//                $frOffer08->setFullReimbursementMaxWinAmount(100);
//                $frOffer08->setFullReimbursementMinParticipants(25);
//                $frOffer08->setFullReimbursementMinTransactionAmount(30);
//                $frOffer08->setFullReimbursementCashbackPercentage(10);
//                $frOffer08->setFullReimbursementTermsAndConditions("Full Reimbursement Terms and conditions");
//                $manager->persist($frOffer08);
//
//                $frOffer09 = new Offer();
//                $frOffer09->setName("Full Reimbursement Offer 09");
//                $frOffer09->setMerchant($this->getReference('merc-04'));
//                $frOffer09->setType(Offer::OFFER_TYPE_FULL_REIMBURSEMENT);
//                $frOffer09->setTranslatableLocale("en");
//                $frOffer09->setDescription("This is Merchant 04's Full Reimbursement Offer number 09");
//                $frOffer09->setProgramId("09");
//                $frOffer09->setRedirectionUri("http://someRedirectionURL.com/09");
//                $frOffer09->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//                $frOffer09->setStartDate(new \DateTime('now'));
//                $frOffer09->setEndDate(new \DateTime('tomorrow'));
//                $frOffer09->setUserGainValue("Upto 100€");
//                $frOffer09->setIsCurrent(true);
//                $frOffer09->setIsArchived(false);
//                $frOffer09->setCreatedAt(new \DateTime());
//                $frOffer09->setUpdatedAt(new \DateTime());
//                $frOffer09->setArchivedAt(new \DateTime());
//                $frOffer09->setCashbackValuePercentage(4);
//                $frOffer09->setFullReimbursementMaxWinAmount(100);
//                $frOffer09->setFullReimbursementMinParticipants(40);
//                $frOffer09->setFullReimbursementMinTransactionAmount(20);
//                $frOffer09->setFullReimbursementCashbackPercentage(10);
//                $frOffer09->setFullReimbursementTermsAndConditions("Full Reimbursement 09 Terms and conditions");
//                $manager->persist($frOffer09);
//
//                $frOffer10 = new Offer();
//                $frOffer10->setName("Full Reimbursement Offer 10");
//                $frOffer10->setMerchant($this->getReference('merc-05'));
//                $frOffer10->setType(Offer::OFFER_TYPE_FULL_REIMBURSEMENT);
//                $frOffer10->setTranslatableLocale("en");
//                $frOffer10->setDescription("This is Merchant 05's Full Reimbursement Offer number 10");
//                $frOffer10->setProgramId("10");
//                $frOffer10->setRedirectionUri("http://someRedirectionURL.com/10");
//                $frOffer10->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//                $frOffer10->setStartDate(new \DateTime('now'));
//                $frOffer10->setEndDate(new \DateTime('tomorrow'));
//                $frOffer10->setUserGainValue("Upto 100€");
//                $frOffer10->setIsCurrent(true);
//                $frOffer10->setIsArchived(false);
//                $frOffer10->setCreatedAt(new \DateTime());
//                $frOffer10->setUpdatedAt(new \DateTime());
//                $frOffer10->setArchivedAt(new \DateTime());
//                $frOffer10->setCashbackValuePercentage(7);
//                $frOffer10->setFullReimbursementMaxWinAmount(100);
//                $frOffer10->setFullReimbursementMinParticipants(25);
//                $frOffer10->setFullReimbursementMinTransactionAmount(30);
//                $frOffer10->setFullReimbursementCashbackPercentage(10);
//                $frOffer10->setFullReimbursementTermsAndConditions("Full Reimbursement 10 Terms and conditions");
//                $manager->persist($frOffer10);
//
//        */
//        $frOffer11 = new Offer();
//        $frOffer11->setName("Full Reimbursement Offer 11");
//        $frOffer11->setMerchant($this->getReference('merc-08'));
//        $frOffer11->setType(Offer::OFFER_TYPE_FULL_REIMBURSEMENT);
//        $frOffer11->setTranslatableLocale("en");
//        $frOffer11->setDescription("This is Merchant 01's Full Reimbursement Offer number 11");
//        $frOffer11->setProgramId("11");
//        $frOffer11->setRedirectionUri("http://someRedirectionURL.com/11");
//        $frOffer11->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//        $frOffer11->setStartDate(new \DateTime('now'));
//        $frOffer11->setEndDate(new \DateTime('tomorrow'));
//        $frOffer11->setUserGainValue("Upto 100€");
//        $frOffer11->setIsCurrent(false);
//        $frOffer11->setIsArchived(true);
//        $frOffer11->setCreatedAt(new \DateTime());
//        $frOffer11->setUpdatedAt(new \DateTime());
//        $frOffer11->setArchivedAt(new \DateTime());
//        $frOffer11->setCashbackValuePercentage(7);
//        $frOffer11->setFullReimbursementMaxWinAmount(100);
//        $frOffer11->setFullReimbursementMinParticipants(25);
//        $frOffer11->setFullReimbursementMinTransactionAmount(30);
//        $frOffer11->setFullReimbursementCashbackPercentage(10);
//        $frOffer11->setFullReimbursementTermsAndConditions("Full Reimbursement 11 Terms and conditions");
//        $manager->persist($frOffer11);
//
//        $frOffer12 = new Offer();
//        $frOffer12->setName("Full Reimbursement Offer 12");
//        $frOffer12->setMerchant($this->getReference('merc-06'));
//        $frOffer12->setType(Offer::OFFER_TYPE_FULL_REIMBURSEMENT);
//        $frOffer12->setTranslatableLocale("en");
//        $frOffer12->setDescription("This is Merchant 02's Full Reimbursement Offer number 12");
//        $frOffer12->setProgramId("12");
//        $frOffer12->setRedirectionUri("http://someRedirectionURL.com/12");
//        $frOffer12->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//        $frOffer12->setStartDate(new \DateTime('now'));
//        $frOffer12->setEndDate(new \DateTime('tomorrow'));
//        $frOffer12->setUserGainValue("Upto 100€");
//        $frOffer12->setIsCurrent(true);
//        $frOffer12->setIsArchived(false);
//        $frOffer12->setCreatedAt(new \DateTime());
//        $frOffer12->setUpdatedAt(new \DateTime());
//        $frOffer12->setArchivedAt(new \DateTime());
//        $frOffer12->setCashbackValuePercentage(7);
//        $frOffer12->setFullReimbursementMaxWinAmount(100);
//        $frOffer12->setFullReimbursementMinParticipants(25);
//        $frOffer12->setFullReimbursementMinTransactionAmount(30);
//        $frOffer12->setFullReimbursementCashbackPercentage(10);
//        $frOffer12->setFullReimbursementTermsAndConditions("Full Reimbursement 12 Terms and conditions");
//        $manager->persist($frOffer12);
//
//        $sgOffer13 = new Offer();
//        $sgOffer13->setName("Subscription Gain Offer 13");
//        $sgOffer13->setMerchant($this->getReference('merc-01'));
//        $sgOffer13->setType(Offer::OFFER_TYPE_SUBSCRIPTION_GAIN);
//        $sgOffer13->setTranslatableLocale("en");
//        $sgOffer13->setDescription("This is Merchant 01's Subscription Gain Offer number 13");
//        $sgOffer13->setProgramId("13");
//        $sgOffer13->setRedirectionUri("http://someRedirectionURL.com/13");
//        $sgOffer13->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//        $sgOffer13->setStartDate(new \DateTime('now'));
//        $sgOffer13->setEndDate(new \DateTime('tomorrow'));
//        $sgOffer13->setUserGainValue("3€");
//        $sgOffer13->setUserGainPercentage(50);
//        $sgOffer13->setIsCurrent(true);
//        $sgOffer13->setIsArchived(false);
//        $sgOffer13->setCreatedAt(new \DateTime());
//        $sgOffer13->setUpdatedAt(new \DateTime());
//        $sgOffer13->setArchivedAt(new \DateTime());
//        $manager->persist($sgOffer13);
//
//        $sgOffer14 = new Offer();
//        $sgOffer14->setName("Subscription Gain Offer 14");
//        $sgOffer14->setMerchant($this->getReference('merc-02'));
//        $sgOffer14->setType(Offer::OFFER_TYPE_SUBSCRIPTION_GAIN);
//        $sgOffer14->setTranslatableLocale("en");
//        $sgOffer14->setDescription("This is Merchant 02's Subscription Gain Offer number 14");
//        $sgOffer14->setProgramId("14");
//        $sgOffer14->setRedirectionUri("http://someRedirectionURL.com/14");
//        $sgOffer14->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//        $sgOffer14->setStartDate(new \DateTime('now'));
//        $sgOffer14->setEndDate(new \DateTime('tomorrow'));
//        $sgOffer14->setUserGainValue("5€");
//        $sgOffer14->setUserGainPercentage(60);
//        $sgOffer14->setIsCurrent(true);
//        $sgOffer14->setIsArchived(false);
//        $sgOffer14->setCreatedAt(new \DateTime());
//        $sgOffer14->setUpdatedAt(new \DateTime());
//        $sgOffer14->setArchivedAt(new \DateTime());
//        $manager->persist($sgOffer14);
//
//        $cbOffer15 = new Offer();
//        $cbOffer15->setName("Cashback Offer 15");
//        $cbOffer15->setMerchant($this->getReference('merc-10'));
//        $cbOffer15->setType(Offer::OFFER_TYPE_CASHBACK);
//        $cbOffer15->setTranslatableLocale("en");
//        $cbOffer15->setDescription("This is Merchant 15's Cashback Offer number 15");
//        $cbOffer15->setProgramId("15");
//        $cbOffer15->setRedirectionUri("http://someRedirectionURL.com/10");
//        $cbOffer15->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//        $cbOffer15->setStartDate(new \DateTime('now'));
//        $cbOffer15->setEndDate(new \DateTime('tomorrow'));
//        $cbOffer15->setUserGainValue("Upto 15%");
//        $cbOffer15->setUserGainPercentage(50);
//        $cbOffer15->setIsCurrent(true);
//        $cbOffer15->setIsArchived(false);
//        $cbOffer15->setCreatedAt(new \DateTime());
//        $cbOffer15->setUpdatedAt(new \DateTime());
//        $cbOffer15->setArchivedAt(new \DateTime());
//        $cbOffer15->setCashbackValuePercentage(15);
//        $manager->persist($cbOffer15);
//
//        $cbOffer16 = new Offer();
//        $cbOffer16->setName("Cashback Offer 07");
//        $cbOffer16->setMerchant($this->getReference('merc-07'));
//        $cbOffer16->setType(Offer::OFFER_TYPE_CASHBACK);
//        $cbOffer16->setTranslatableLocale("en");
//        $cbOffer16->setDescription("This is Merchant 15's Cashback Offer number 07");
//        $cbOffer16->setProgramId("07");
//        $cbOffer16->setRedirectionUri("http://someRedirectionURL.com/07");
//        $cbOffer16->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//        $cbOffer16->setStartDate(new \DateTime('now'));
//        $cbOffer16->setEndDate(new \DateTime('tomorrow'));
//        $cbOffer16->setUserGainValue("Upto 16€");
//        $cbOffer16->setUserGainPercentage(50);
//        $cbOffer16->setIsCurrent(true);
//        $cbOffer16->setIsArchived(false);
//        $cbOffer16->setCreatedAt(new \DateTime());
//        $cbOffer16->setUpdatedAt(new \DateTime());
//        $cbOffer16->setArchivedAt(new \DateTime());
//        $cbOffer16->setCashbackValueAmount(16);
//        $manager->persist($cbOffer16);
//
//
//        $cbOffer17 = new Offer();
//        $cbOffer17->setName("Cashback Offer 09");
//        $cbOffer17->setMerchant($this->getReference('merc-09'));
//        $cbOffer17->setType(Offer::OFFER_TYPE_CASHBACK);
//        $cbOffer17->setTranslatableLocale("en");
//        $cbOffer17->setDescription("This is Merchant 09's Cashback Offer number 09");
//        $cbOffer17->setProgramId("09");
//        $cbOffer17->setRedirectionUri("http://someRedirectionURL.com/09");
//        $cbOffer17->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//        $cbOffer17->setStartDate(new \DateTime('now'));
//        $cbOffer17->setEndDate(new \DateTime('tomorrow'));
//        $cbOffer17->setUserGainValue("Upto 15€");
//        $cbOffer17->setUserGainPercentage(50);
//        $cbOffer17->setIsCurrent(true);
//        $cbOffer17->setIsArchived(false);
//        $cbOffer17->setCreatedAt(new \DateTime());
//        $cbOffer17->setUpdatedAt(new \DateTime());
//        $cbOffer17->setArchivedAt(new \DateTime());
//        $cbOffer17->setCashbackValueAmount(15);
//        $manager->persist($cbOffer17);
//
//        $cpOffer18 = new Offer();
//        $cpOffer18->setName("Code Promo Offer 18");
//        $cpOffer18->setMerchant($this->getReference('merc-05'));
//        $cpOffer18->setType(Offer::OFFER_TYPE_CODE_PROMO);
//        $cpOffer18->setTranslatableLocale("en");
//        $cpOffer18->setDescription("This is Merchant 05's Code Promo Offer number 18");
//        $cpOffer18->setProgramId("18");
//        $cpOffer18->setRedirectionUri("http://someRedirectionURL.com/18");
//        $cpOffer18->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//        $cpOffer18->setStartDate(new \DateTime('now'));
//        $cpOffer18->setEndDate(new \DateTime('tomorrow'));
//        $cpOffer18->setUserGainValue("CODE2233");
//        $cpOffer18->setIsCurrent(true);
//        $cpOffer18->setIsArchived(false);
//        $cpOffer18->setCreatedAt(new \DateTime());
//        $cpOffer18->setUpdatedAt(new \DateTime());
//        $cpOffer18->setArchivedAt(new \DateTime());
//        $manager->persist($cpOffer18);
//
//        $cpOffer19 = new Offer();
//        $cpOffer19->setName("Code Promo Offer 19");
//        $cpOffer19->setMerchant($this->getReference('merc-03'));
//        $cpOffer19->setType(Offer::OFFER_TYPE_CODE_PROMO);
//        $cpOffer19->setTranslatableLocale("en");
//        $cpOffer19->setDescription("This is Merchant 03's Code Promo Offer number 19");
//        $cpOffer19->setProgramId("19");
//        $cpOffer19->setRedirectionUri("http://someRedirectionURL.com/19");
//        $cpOffer19->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//        $cpOffer19->setStartDate(new \DateTime('now'));
//        $cpOffer19->setEndDate(new \DateTime('tomorrow'));
//        $cpOffer19->setUserGainValue("CODE2233");
//        $cpOffer19->setIsCurrent(true);
//        $cpOffer19->setIsArchived(false);
//        $cpOffer19->setCreatedAt(new \DateTime());
//        $cpOffer19->setUpdatedAt(new \DateTime());
//        $cpOffer19->setArchivedAt(new \DateTime());
//        $manager->persist($cpOffer19);
//
//        $cpOffer20 = new Offer();
//        $cpOffer20->setName("Code Promo Offer 20");
//        $cpOffer20->setMerchant($this->getReference('merc-03'));
//        $cpOffer20->setType(Offer::OFFER_TYPE_CODE_PROMO);
//        $cpOffer20->setTranslatableLocale("en");
//        $cpOffer20->setDescription("This is Merchant 03's Code Promo Offer number 20");
//        $cpOffer20->setProgramId("20");
//        $cpOffer20->setRedirectionUri("http://someRedirectionURL.com/20");
//        $cpOffer20->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//        $cpOffer20->setStartDate(new \DateTime('now'));
//        $cpOffer20->setEndDate(new \DateTime('tomorrow'));
//        $cpOffer20->setUserGainValue("CODE2244");
//        $cpOffer20->setIsCurrent(true);
//        $cpOffer20->setIsArchived(false);
//        $cpOffer20->setCreatedAt(new \DateTime());
//        $cpOffer20->setUpdatedAt(new \DateTime());
//        $cpOffer20->setArchivedAt(new \DateTime());
//        $manager->persist($cpOffer20);
//
//        $cpOffer21 = new Offer();
//        $cpOffer21->setName("Code Promo Offer 21");
//        $cpOffer21->setMerchant($this->getReference('merc-06'));
//        $cpOffer21->setType(Offer::OFFER_TYPE_CODE_PROMO);
//        $cpOffer21->setTranslatableLocale("en");
//        $cpOffer21->setDescription("This is Merchant 06's Code Promo Offer number 21");
//        $cpOffer21->setProgramId("21");
//        $cpOffer21->setRedirectionUri("http://someRedirectionURL.com/21");
//        $cpOffer21->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//        $cpOffer21->setStartDate(new \DateTime('now'));
//        $cpOffer21->setEndDate(new \DateTime('tomorrow'));
//        $cpOffer21->setUserGainValue("CODE2233");
//        $cpOffer21->setIsCurrent(true);
//        $cpOffer21->setIsArchived(false);
//        $cpOffer21->setCreatedAt(new \DateTime());
//        $cpOffer21->setUpdatedAt(new \DateTime());
//        $cpOffer21->setArchivedAt(new \DateTime());
//        $manager->persist($cpOffer21);
//        /*
//                $frOffer22 = new Offer();
//                $frOffer22->setName("Full Reimbursement Offer 22");
//                $frOffer22->setMerchant($this->getReference('merc-05'));
//                $frOffer22->setType(Offer::OFFER_TYPE_FULL_REIMBURSEMENT);
//                $frOffer22->setTranslatableLocale("en");
//                $frOffer22->setDescription("This is Merchant 05's Full Reimbursement Offer number 22");
//                $frOffer22->setProgramId("22");
//                $frOffer22->setRedirectionUri("http://someRedirectionURL.com/22");
//                $frOffer22->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//                $frOffer22->setStartDate(new \DateTime('now'));
//                $frOffer22->setEndDate(new \DateTime('tomorrow'));
//                $frOffer22->setUserGainValue("Upto 100€");
//                $frOffer22->setIsCurrent(true);
//                $frOffer22->setIsArchived(false);
//                $frOffer22->setCreatedAt(new \DateTime());
//                $frOffer22->setUpdatedAt(new \DateTime());
//                $frOffer22->setArchivedAt(new \DateTime());
//                $frOffer22->setCashbackValuePercentage(7);
//                $frOffer22->setFullReimbursementMaxWinAmount(100);
//                $frOffer22->setFullReimbursementMinParticipants(25);
//                $frOffer22->setFullReimbursementMinTransactionAmount(30);
//                $frOffer22->setFullReimbursementCashbackPercentage(10);
//                $frOffer22->setFullReimbursementTermsAndConditions("Full Reimbursement Terms and conditions");
//                $manager->persist($frOffer22);
//
//                $frOffer24 = new Offer();
//                $frOffer24->setName("Full Reimbursement Offer 24");
//                $frOffer24->setMerchant($this->getReference('merc-02'));
//                $frOffer24->setType(Offer::OFFER_TYPE_FULL_REIMBURSEMENT);
//                $frOffer24->setTranslatableLocale("en");
//                $frOffer24->setDescription("This is Merchant 02's Full Reimbursement Offer number 24");
//                $frOffer24->setProgramId("24");
//                $frOffer24->setRedirectionUri("http://someRedirectionURL.com/24");
//                $frOffer24->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//                $frOffer24->setStartDate(new \DateTime('now'));
//                $frOffer24->setEndDate(new \DateTime('tomorrow'));
//                $frOffer24->setUserGainValue("Upto 240€");
//                $frOffer24->setIsCurrent(true);
//                $frOffer24->setIsArchived(false);
//                $frOffer24->setCreatedAt(new \DateTime());
//                $frOffer24->setUpdatedAt(new \DateTime());
//                $frOffer24->setArchivedAt(new \DateTime());
//                $frOffer24->setCashbackValuePercentage(7);
//                $frOffer24->setFullReimbursementMaxWinAmount(240);
//                $frOffer24->setFullReimbursementMinParticipants(25);
//                $frOffer24->setFullReimbursementMinTransactionAmount(30);
//                $frOffer24->setFullReimbursementCashbackPercentage(24);
//                $frOffer24->setFullReimbursementTermsAndConditions("Full Reimbursement 24 Terms and conditions");
//                $manager->persist($frOffer24);
//
//                $frOffer25 = new Offer();
//                $frOffer25->setName("Full Reimbursement Offer 25");
//                $frOffer25->setMerchant($this->getReference('merc-05'));
//                $frOffer25->setType(Offer::OFFER_TYPE_FULL_REIMBURSEMENT);
//                $frOffer25->setTranslatableLocale("en");
//                $frOffer25->setDescription("This is Merchant 15's Full Reimbursement Offer number 25");
//                $frOffer25->setProgramId("25");
//                $frOffer25->setRedirectionUri("http://someRedirectionURL.com/25");
//                $frOffer25->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//                $frOffer25->setStartDate(new \DateTime('now'));
//                $frOffer25->setEndDate(new \DateTime('tomorrow'));
//                $frOffer25->setUserGainValue("Upto 100€");
//                $frOffer25->setIsCurrent(false);
//                $frOffer25->setIsArchived(true);
//                $frOffer25->setCreatedAt(new \DateTime());
//                $frOffer25->setUpdatedAt(new \DateTime());
//                $frOffer25->setArchivedAt(new \DateTime());
//                $frOffer25->setCashbackValuePercentage(7);
//                $frOffer25->setFullReimbursementMaxWinAmount(100);
//                $frOffer25->setFullReimbursementMinParticipants(25);
//                $frOffer25->setFullReimbursementMinTransactionAmount(30);
//                $frOffer25->setFullReimbursementCashbackPercentage(10);
//                $frOffer25->setFullReimbursementTermsAndConditions("Full Reimbursement 25 Terms and conditions");
//                $manager->persist($frOffer25);
//        */
//
//        $frOffer26 = new Offer();
//        $frOffer26->setName("Full Reimbursement Offer 26");
//        $frOffer26->setMerchant($this->getReference('merc-03'));
//        $frOffer26->setType(Offer::OFFER_TYPE_FULL_REIMBURSEMENT);
//        $frOffer26->setTranslatableLocale("en");
//        $frOffer26->setDescription("This is Merchant 16's Full Reimbursement Offer number 26");
//        $frOffer26->setProgramId("26");
//        $frOffer26->setRedirectionUri("http://someRedirectionURL.com/26");
//        $frOffer26->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//        $frOffer26->setStartDate(new \DateTime('now'));
//        $frOffer26->setEndDate(new \DateTime('tomorrow'));
//        $frOffer26->setUserGainValue("Upto 100€");
//        $frOffer26->setIsCurrent(true);
//        $frOffer26->setIsArchived(false);
//        $frOffer26->setCreatedAt(new \DateTime());
//        $frOffer26->setUpdatedAt(new \DateTime());
//        $frOffer26->setArchivedAt(new \DateTime());
//        $frOffer26->setCashbackValuePercentage(7);
//        $frOffer26->setFullReimbursementMaxWinAmount(100);
//        $frOffer26->setFullReimbursementMinParticipants(25);
//        $frOffer26->setFullReimbursementMinTransactionAmount(30);
//        $frOffer26->setFullReimbursementCashbackPercentage(10);
//        $frOffer26->setFullReimbursementTermsAndConditions("Full Reimbursement 26 Terms and conditions");
//        $manager->persist($frOffer26);
//        /*
//                $sgOffer27 = new Offer();
//                $sgOffer27->setName("Subscription Gain Offer 27");
//                $sgOffer27->setMerchant($this->getReference('merc-05'));
//                $sgOffer27->setType(Offer::OFFER_TYPE_SUBSCRIPTION_GAIN);
//                $sgOffer27->setTranslatableLocale("en");
//                $sgOffer27->setDescription("This is Merchant 15's Subscription Gain Offer number 27");
//                $sgOffer27->setProgramId("27");
//                $sgOffer27->setRedirectionUri("http://someRedirectionURL.com/27");
//                $sgOffer27->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//                $sgOffer27->setStartDate(new \DateTime('now'));
//                $sgOffer27->setEndDate(new \DateTime('tomorrow'));
//                $sgOffer27->setUserGainValue("3€");
//                $sgOffer27->setUserGainPercentage(50);
//                $sgOffer27->setIsCurrent(true);
//                $sgOffer27->setIsArchived(false);
//                $sgOffer27->setCreatedAt(new \DateTime());
//                $sgOffer27->setUpdatedAt(new \DateTime());
//                $sgOffer27->setArchivedAt(new \DateTime());
//                $manager->persist($sgOffer27);
//        */
//
//        $sgOffer28 = new Offer();
//        $sgOffer28->setName("Subscription Gain Offer 28");
//        $sgOffer28->setMerchant($this->getReference('merc-03'));
//        $sgOffer28->setType(Offer::OFFER_TYPE_SUBSCRIPTION_GAIN);
//        $sgOffer28->setTranslatableLocale("en");
//        $sgOffer28->setDescription("This is Merchant 16's Subscription Gain Offer number 28");
//        $sgOffer28->setProgramId("28");
//        $sgOffer28->setRedirectionUri("http://someRedirectionURL.com/28");
//        $sgOffer28->setDisplayUri("http://wowdesigns.in/projects/gd/images/transparent-1x1.png");
//        $sgOffer28->setStartDate(new \DateTime('now'));
//        $sgOffer28->setEndDate(new \DateTime('tomorrow'));
//        $sgOffer28->setUserGainValue("5€");
//        $sgOffer28->setUserGainPercentage(60);
//        $sgOffer28->setIsCurrent(true);
//        $sgOffer28->setIsArchived(false);
//        $sgOffer28->setCreatedAt(new \DateTime());
//        $sgOffer28->setUpdatedAt(new \DateTime());
//        $sgOffer28->setArchivedAt(new \DateTime());
//        $manager->persist($sgOffer28);
//
//        $manager->flush();
//        
//        $this->addReference('offer-01', $cbOffer01);
//        $this->addReference('offer-02', $cbOffer02);
//        $this->addReference('offer-03', $cbOffer03);
//        $this->addReference('fr-offer-11', $frOffer11);
//        $this->addReference('fr-offer-12', $frOffer12);
//        $this->addReference('sg-offer-13', $sgOffer13);
//        $this->addReference('sg-offer-14', $sgOffer14);
//        $this->addReference('fr-offer-26', $frOffer26);
    }

    public function getOrder()
    {
        return 14;
    }
}
